DROP TABLE IF EXISTS utilisateurs;
CREATE TABLE utilisateurs (
    ID_user INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    adresse TEXT NOT NULL,
    Date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
